required = [
  "github.com/golang/dep/cmd/dep",
  "github.com/jteeuwen/go-bindata/go-bindata",
  "github.com/flynn/go-tuf/cmd/tuf",
  "github.com/flynn/go-tuf/cmd/tuf-client",
]

[prune]
  non-go = true
  go-tests = true
  unused-packages = true

[[constraint]]
  branch = "datetimes"
  name = "github.com/BurntSushi/toml"

[[constraint]]
  branch = "master"
  name = "github.com/cupcake/jsonschema"

[[constraint]]
  name = "github.com/docker/go-units"
  version = "0.3.0"

[[constraint]]
  branch = "v1"
  name = "github.com/flynn/go-check"

[[constraint]]
  branch = "master"
  name = "github.com/flynn/go-docopt"

[[constraint]]
  branch = "master"
  name = "github.com/flynn/go-p9p"

[[constraint]]
  branch = "master"
  name = "github.com/flynn/go-tuf"

[[constraint]]
  branch = "master"
  name = "github.com/flynn/que-go"

[[constraint]]
  branch = "master"
  name = "github.com/flynn/tail"

[[constraint]]
  name = "github.com/golang/dep"
  version = "v0.5.0"

[[constraint]]
  name = "github.com/inconshreveable/log15"
  version = "2.13.0"

[[constraint]]
  name = "github.com/jtacoma/uritemplates"
  version = "1.0.0"

[[constraint]]
  branch = "master"
  name = "github.com/opencontainers/runc"
  source = "https://github.com/flynn/runc"

[[constraint]]
  branch = "master"
  name = "github.com/tent/canonical-json-go"

[[constraint]]
  branch = "master"
  name = "github.com/tiborvass/uniline"

[[constraint]]
  branch = "master"
  name = "github.com/vanillahsu/go_reuseport"

[[constraint]]
  branch = "v0"
  name = "gopkg.in/inconshreveable/go-update.v0"

[[constraint]]
  branch = "master"
  name = "github.com/jvatic/asset-matrix-go"

[[constraint]]
  name = "github.com/golang/protobuf"
  revision = "1d3f30b51784bec5aad268e59fd3c2fc1c2fe73f"

[[constraint]]
  branch = "master"
  name = "google.golang.org/genproto"

[[constraint]]
  name = "google.golang.org/grpc"
	version = "1.22.1"

[[constraint]]
  name = "github.com/improbable-eng/grpc-web"
	version = "v0.9.6"

[[constraint]]
  name = "github.com/soheilhy/cmux"
  version = "0.1.4"

[[constraint]]
  name = "github.com/grpc-ecosystem/go-grpc-middleware"
  version = "1.0.0"
